spring:
  data:
    redis:
      host: moodly-redis
      port: 6379

  datasource:
    url: jdbc:mysql://moodly-cart-db:3306/moodly_cart?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: when-authorized
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

security:
  jwt:
    common:
      secret: ${JWT_SECRET}

product-service:
  base-url: http://moodly-product:8083

eureka:
  client:
    service-url:
      defaultZone: http://moodly-eurekaserver:8070/eureka

info:
  app:
    name: "cart-service"
    description: "docker"