spring:
  data:
    redis:
      host: moodly-redis
      port: 6379
      connect-timeout: 2s
      timeout: 1s

eureka:
  client:
    service-url:
      defaultZone: http://moodly-eurekaserver:8070/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    health:
      show-details: never

    gateway:
      access: unrestricted

  info:
    env:
      enabled: false

security:
  jwt:
    common:
      secret: ${JWT_SECRET}
